### ISSUE TITLE
mediaGroup param is not immutable

### ISSUE THREAD

**Issue by AlexOwl** [nitreojs/puregram#99]
## the bug
mediaGroup объект ломается после его использования в context.replyWithMediaGroup
до: [{ type: 'video', media: { type: 'url', value: '***'; } } ]
после [{ type: 'video', media: '[***'](***); }]

(с полем media что-то странное происходит)

## steps to reproduce
steps to reproduce the behavior:
console.log("до", mediaGroup)
await context.replyWithMediaGroup(mediaGroup) // у меня тут ошибка иногда вылезает и хочу переотправить запрос
console.log("после", mediaGroup)

## expected behavior
от использования mediaGroup, не он не должен меняться по рефу

## environment
| package         | version |
| :-----------:   | :-----: |
| `puregram`      | `X.Y.Z` |
| `node`          | `X.Y.Z` |
| `TypeScript`    | `X.Y.Z` |
| `yarn` or `npm` | `X.Y.Z` |

## additional context
я не смог трейснуть ошибку в коде у тебя, надо чекать более детально, пока дерти фикс повесил 
```
static fixUrl(mediaGroup: SendMediaGroupParams["media"]) {
        mediaGroup.forEach((inputMedia) => Object.assign(
                inputMedia,
                typeof inputMedia.media === "string" ||
                    inputMedia.media instanceof String
                    ? {
                          media: MediaSource.url(
                              inputMedia.media as unknown as string,
                          ),
                      }
                    : {},
            ));
    }
```

юзеркейс такой:
попробовать отправить url просто, иногда в телеге не проходит, например сыпет ошибку WEBPAGE_CURL_FAILED или Wrong file identifier/HTTP URL specified, пробую переотправить с тем же mediaGroup - ловлю ошибку ```Error on reply TypeError: expected media to be created via MediaSource at Telegram.createAttachMediaInput (/app/node_modules/puregram/lib/telegram.js:257:19)``` , если еще раз запрос не пройдет, то переотправить с forceUpload: true (ну тут я уже конвертаю, но в том числе, прошлый mediaGroup неюзабельный)

плюс еще странно что тайпскрипт не спас на билде, потому что media становится строкой как я понял и там его вообще не может быть, по типам

**Comment by AlexOwl** [comment]
Точно где-то меняется, сейчас вот такую словил

```
error: APIError: Bad Request: can't parse InputMedia: media not found

at Telegram._callAPI (/app/node_modules/puregram/lib/telegram.js:392:23)

at processTicksAndRejections (node:internal/process/task_queues:95:5)

at MessageContext.sendMediaGroup (/app/node_modules/puregram/lib/contexts/mixins/send.js:204:26) {

code: 400,

cause: undefined

}

}

mediaGroup2 [ { type: 'video', media: 'attach://7fd62a5c6a6f8436' } ]
```
